### ISSUE TITLE
How to build this library on Windows 10?

### ISSUE THREAD

**Issue by igaryhe** [gpg-rs/gpgme#30]
Hi all,
I'm thinking about creating a cross-platform pass compatible application, and I wish to use this library. However, I failed to build this library. Currently do this library support Windows 10?

**Comment by johnschug** [comment]
Windows is not supported. However, it may be possible to use these bindings if you can somehow get rust to correctly link to the gpgme libraries (see the environment variables in the readme). I have never gotten it to work though.

**Comment by SirWindfield** [comment]
Are there alternatives that someone on Windows can use? I want to use `git2` and allow for signed commits :)
