### ISSUE TITLE
provide a changelog?

### ISSUE THREAD

**Issue by dkg** [gpg-rs/gpgme#42]
Thanks for the recent updates to libgpg-error and gpgme. I note that the versions incremented in a [semver](https://semver.org/)-incompatible way (from 0.10.x to 0.11), which means every downstream project that depends on them will itself need to adjust its dependencies and confirm that it works with whatever API changes are supplied.

It would be useful to downstream projects if there were a changelog that made clear what adjustments they need to make when moving across a semver-incompatible version.

**Comment by johnschug** [comment]
I've added a list of breaking changes in the [release](https://github.com/gpg-rs/gpgme/releases/tag/v0.11.0) for the new version
